### ISSUE TITLE
Download files feature

### ISSUE THREAD

**Issue by cesards** [dimaslz/navtree#3]
Congratz man! This is the Octotree replacemente. However, I love the Octotree feature of downloading repo files. Is there any way you could implement this?

<img width="210" alt="screen shot 2016-05-01 at 18 01 37" src="https://cloud.githubusercontent.com/assets/1536079/14942752/cf3d8924-0fc6-11e6-8223-bbd30d28db11.png">

**Comment by dimaslz** [comment]
Hi @cesards 

I like your feedback. Good feature! this weekend I will try to add it.

Thanks a lot!

PD: Sorry for the delay :)

**Comment by cesards** [comment]
Haha thanks to you 👍 

@orestes spoiled me about your repo. Nicely done!!!!

;-)

Also, I suggest you creating a couple of tags. I wanted to tag it as "enhancement" but I couldn't, in order to make your life easier in order to distinguish between bugs and "nice to have"

**Comment by dimaslz** [comment]
Hi @cesards Your wish is done! Update your extension.

Thanks a lot. Kind regards!

**Comment by cesards** [comment]
![thank you](https://cloud.githubusercontent.com/assets/1536079/15208700/eddaf978-1824-11e6-8ef8-0a65cc560601.gif)

See ya! ;-)
